name: test-faas-cli

on: [pull_request]

jobs:
  test_faas_cli_action:
    runs-on: ubuntu-latest
    permissions: {}
    name: Install faas-cli and test presence in path
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
    - name: Install faas-cli
      uses: ./
    - name: Check install!
      run: faas-cli version
    - name: Check root directory
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo 'should be clean'
          exit 1
        else
          exit 0
        fi

  test_faas_cli_action_custom:
    runs-on: ubuntu-latest
    permissions: {}

    name: Install Custom faas-cli and test presence in path
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
    - name: Install faas-cli
      uses: ./
      with:
        faas-cli-release: '0.13.15'
    - name: Check install!
      run: faas-cli version
    - name: Check root directory
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo 'should be clean'
          exit 1
        else
          exit 0
        fi

  test_faas_cli_action_wrong:
    runs-on: ubuntu-latest
    permissions: {}
    name: Try to install a wrong Cosign
    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
    - name: Install faas-cli
      uses: ./
      with:
        faas-cli-release: 'honk'
      continue-on-error: true
