name: test-faas-cli

on: [pull_request]

jobs:
  test_faas_cli_action:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    name: Install faas-cli and test presence in path
    steps:
    - uses: actions/checkout@v4
    - name: Install faas-cli
      uses: ./
    - name: Check install!
      run: faas-cli version
    - name: Check root directory
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo 'should be clean'
          exit 1
        else
          exit 0
        fi

  test_faas_cli_action_custom:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    name: Install Custom faas-cli and test presence in path
    steps:
    - uses: actions/checkout@v4
    - name: Install faas-cli
      uses: ./
      with:
        faas-cli-release: '0.13.15'
    - name: Check install!
      run: faas-cli version
    - name: Check root directory
      run: |
        if [[ $(git diff --stat) != '' ]]; then
          echo 'should be clean'
          exit 1
        else
          exit 0
        fi

  test_faas_cli_action_wrong:
    runs-on: ubuntu-latest
    permissions:
      actions: none
      checks: none
      contents: none
      deployments: none
      issues: none
      packages: none
      pull-requests: none
      repository-projects: none
      security-events: none
      statuses: none
    name: Try to install a wrong Cosign
    steps:
    - uses: actions/checkout@v4
    - name: Install faas-cli
      uses: ./
      with:
        faas-cli-release: 'honk'
      continue-on-error: true
